In [2]:
import numpy as np
import torch

In [3]:
print(torch.cuda.is_available())

False


In [7]:
t = torch.tensor(([5,6,9],[6,9,10]))
t.size()

torch.Size([2, 3])

In [4]:
arr = np.ones((3,3))
print("数据类型为：",arr.dtype)
t = torch.tensor(arr)
print(t)
print(t.device)
print(t.layout)
print(t.dtype)

数据类型为： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
cpu
torch.strided
torch.float64


In [6]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [8]:
t1 = torch.tensor([3,5,6])
# t2 = t1.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [9]:
arr = np.array([2,3,5,6,7])
x1 = torch.Tensor(arr)
x2 = torch.tensor(arr)
x3 = torch.as_tensor(arr)
x4 = torch.from_numpy(arr)

In [10]:
x1

tensor([2., 3., 5., 6., 7.])

In [11]:
x2

tensor([2, 3, 5, 6, 7], dtype=torch.int32)

In [12]:
x3

tensor([2, 3, 5, 6, 7], dtype=torch.int32)

In [13]:
x4

tensor([2, 3, 5, 6, 7], dtype=torch.int32)